---
- ansible.builtin.import_role:
    name: infrastructure/build_vars
  vars:
    service: photoprism

- name: "Ensure {{ photoprism.user.name }} is created"
  ansible.builtin.import_role:
    name: infrastructure/user
  vars:
    user_name: "{{ photoprism.user.name }}"
    user_password: "{{ photoprism.user.password }}"

- name: Ensure photoprism storage directory location exists
  ansible.builtin.import_role:
    name: infrastructure/service-data-directory
  vars:
    data_storage: "{{ photoprism.data_storage }}"
    user: "{{ photoprism.user.name }}"

- name: Ensure photoprism is running
  become: true
  become_user: "{{ photoprism.user.name }}"
  block:
    - name: Ensure photoprism container network is created
      containers.podman.podman_network:
        name: "{{ photoprism.container.network }}"
        driver: bridge
        recreate: false
        state: present

    - import_tasks: photoprism-database.yaml
    - import_tasks: photoprism-server.yaml

