---
- name: Ensure redis data location exists
  ansible.builtin.file:
    path: "{{ immich.container.redis.storage.data }}"
    state: directory
    owner: "{{ immich.user.name }}"
    group: "{{ immich.user.name }}"
    mode: 0755

- name: Instantiate immich-redis container
  ansible.builtin.import_role:
    name: infrastructure/container
  vars:
    container_name: immich_redis
    container_image: "{{ immich.container.redis.image }}"
    container_image_tag: "{{ immich.container.redis.tag }}"
    container_volumes:
      - "{{ immich.container.redis.storage.data }}:/data:rw"
    container_networks:
      - "{{ immich.container.network }}"
    container_network_aliases:
      - redis
    container_user: "{{ immich.user.name }}"

