---
- name: Ensure immich postgres data location exists
  ansible.builtin.file:
    path: "{{ immich.container.postgres.storage.data }}"
    state: directory
    owner: "{{ immich.user.name }}"
    group: "{{ immich.user.name }}"
    mode: 0755

- name: Instantiate immich-postgres container
  ansible.builtin.import_role:
    name: infrastructure/container
  vars:
    container_name: immich_postgres
    container_image: "{{ immich.container.postgres.image }}"
    container_image_tag: "{{ immich.container.postgres.tag }}"
    container_env:
      POSTGRES_DB: "{{ immich.container.postgres.config.db.name }}"
      POSTGRES_USER: "{{ immich.container.postgres.config.db.username }}"
      POSTGRES_PASSWORD: "{{ immich.container.postgres.config.db.password }}"
      POSTGRES_INITDB_ARGS: "--data-checksums"
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      DB_STORAGE_TYPE: "HDD"
    container_volumes:
      - "{{ immich.container.postgres.storage.data }}:/var/lib/postgresql/data"
    container_networks:
      - "{{ immich.container.network }}"
    container_network_aliases:
      - database
    container_user: "{{ immich.user.name }}"

