---
# Traefik
traefik_user: traefik-user
traefik_storage_directory: "/home/{{ traefik_user }}/traefik-storage"
traefik_config_location: "{{ traefik_storage_directory }}/config"
traefik_config_dynamic_location: "{{ traefik_storage_directory }}/config_dynamic"
traefik_image: docker.io/traefik
traefik_tag: v3.5.1
traefik_web_port: 10080
traefik_websecure_port: 10443

wol_poweroff_user: wol-poweroff-user

