---
- name: Instantiate karakeep-chrome container
  ansible.builtin.include_role:
    name: infrastructure/container
  vars:
    container_name: karakeep_chrome
    container_image: "{{ karakeep_chrome_image }}"
    container_image_tag: "{{ karakeep_chrome_tag }}"
    container_command:
      - "--no-sandbox"
      - "--disable-gpu"
      - "--disable-dev-shm-usage"
      - "--remote-debugging-address=0.0.0.0"
      - "--remote-debugging-port=9222"
      - "--hide-scrollbars"
    container_networks:
      - "{{ karakeep_network }}"
    container_network_aliases:
      - chrome
    container_user: "{{ karakeep_user }}"

