---
- name: Instantiate karakeep-chrome container
  ansible.builtin.import_role:
    name: infrastructure/container
  vars:
    container_name: karakeep_chrome
    container_image: "{{ karakeep.container.chrome.image }}"
    container_image_tag: "{{ karakeep.container.chrome.tag }}"
    container_command:
      - "--no-sandbox"
      - "--disable-gpu"
      - "--disable-dev-shm-usage"
      - "--remote-debugging-address=0.0.0.0"
      - "--remote-debugging-port=9222"
      - "--hide-scrollbars"
    container_networks:
      - "{{ karakeep.container.network }}"
    container_network_aliases:
      - chrome
    container_user: "{{ karakeep.user.name }}"

