---
domain: dev.homelab.mikemarti.ch
platform: debian
superuser_method: sudo
server_superuser_method: doas

# Traefik
traefik_user_password: "123456"
traefik_ca_server: "https://acme-staging-v02.api.letsencrypt.org/directory"
traefik_dashboard_username: admin
traefik_dashboard_password: admin

# Pihole
pihole_user_password: "123456"
pihole_admin_username: admin
pihole_admin_password: admin

# Home Assistant
homeassistant_user_password: "123456"
homeassistant_mosquitto_homeassistant_username: homeassistant
homeassistant_mosquitto_homeassistant_password: homeassistant
homeassistant_mosquitto_zigbee2mqtt_username: zigbee2mqtt
homeassistant_mosquitto_zigbee2mqtt_password: zigbee2mqtt
homeassistant_zigbee2mqtt_frontend_auth_token: admin
homeassistant_zigbee2mqtt_zigbee_device_id_serial: 00000
homeassistant_zigbee2mqtt_zigbee_device_id: /dev/null
homeassistant_server_wol_poweroff_user_ssh_private_key_base64: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNDNU1uRHdPbDFveERIN1d5OE5oRngwQ29EQ2RLTUdsVlB0ZVhISUd0S2h2d0FBQUppeDZBdWlzZWdMCm9nQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQzVNbkR3T2wxb3hESDdXeThOaEZ4MENvRENkS01HbFZQdGVYSElHdEtodncKQUFBRUFpQmo0V1AwTFVkc2lLeUNtY011RlkwMENmSWNsSThZc2NoNnY1WkJmMzFMa3ljUEE2WFdqRU1mdGJMdzJFWEhRSwpnTUowb3dhVlUrMTVjY2dhMHFHL0FBQUFGRzFwYTJWQWJXbHJaUzFvYjIxbExXeHBiblY0QVE9PQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K

# Karakeep
karakeep_user_password: "123456"
karakeep_nextauth_secret: karakeep_nextauth_secret
karakeep_meilisearch_master_key: karakeep_meilisearch_master_key
karakeep_disable_signups: "false"

