---
domain: dev.homelab.mikemarti.ch
superuser_method: sudo
server_superuser_method: doas

traefik_env:
  user:
    password: "123456"
  container:
    server:
      config:
        ca_server: "https://acme-staging-v02.api.letsencrypt.org/directory"
        dashboard:
          username: admin
          password: admin

pihole_env:
  user:
    password: "123456"
  container:
    server:
      config:
        admin:
          username: admin
          password: admin

homeassistant_env:
  user:
    password: "123456"
  container:
    server:
      config:
        # This private key can be used to locally test the remote poweroff functionality of the server.
        # It is intended for local development only and should not be used with real systems. For
        # non-local environments a new ssh key pair can be created using ssh-keygen.
        # DO NOT USE IN PRODUCTION UNDER ANY CIRCUMSTANCES!!
        wol_poweroff_user_ssh_private_key_base64: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNDNU1uRHdPbDFveERIN1d5OE5oRngwQ29EQ2RLTUdsVlB0ZVhISUd0S2h2d0FBQUppeDZBdWlzZWdMCm9nQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQzVNbkR3T2wxb3hESDdXeThOaEZ4MENvRENkS01HbFZQdGVYSElHdEtodncKQUFBRUFpQmo0V1AwTFVkc2lLeUNtY011RlkwMENmSWNsSThZc2NoNnY1WkJmMzFMa3ljUEE2WFdqRU1mdGJMdzJFWEhRSwpnTUowb3dhVlUrMTVjY2dhMHFHL0FBQUFGRzFwYTJWQWJXbHJaUzFvYjIxbExXeHBiblY0QVE9PQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K
    mosquitto:
      config:
        homeassistant:
          username: homeassistant
          password: homeassistant
        zigbee2mqtt:
          username: zigbee2mqtt
          password: zigbee2mqtt
    zigbee2mqtt:
      config:
        frontend_auth_token: admin
        zigbee_device_id_serial: 00000
        zigbee_device_id: /dev/null

karakeep_env:
  user:
    password: "123456"
  container:
    server:
      config:
        nextauth_secret: karakeep_nextauth_secret
        disable_signups: "false"
    meilisearch:
      config:
        master_key: karakeep_meilisearch_master_key

