---
domain: dev.homelab.mikemarti.ch
superuser_method: sudo

zfs_env:
  devices:
    - /dev/vdb
    - /dev/vdc

# This public key is the counterpart to the private ssh key found in the pi variable file. It is stored as an authorized
# key for the wol_poweroff_user, such that a remote actor with the private key counterpart can initiate a remote poweroff
# command through an unprivileged user. In order to not need to deploy all nodes simultaneously, a key pair was created
# ahead of time and stored in the variable files, as opposed to creating one during ansible execution time. The key
# presented here is intended for local development only and should not be used with real systems. For non-local
# environments a new ssh key pair can be created using ssh-keygen.
# DO NOT USE IN PRODUCTION UNDER ANY CIRCUMSTANCES!!
wol_poweroff_user_ssh_public_key_base64: c3NoLWVkMjU1MTkgQUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSUxreWNQQTZYV2pFTWZ0Ykx3MkVYSFFLZ01KMG93YVZVKzE1Y2NnYTBxRy8gbWlrZUBtaWtlLWhvbWUtbGludXgK

traefik_env:
  user:
    password: "123456"
  container:
    server:
      config:
        ca_server: "https://acme-staging-v02.api.letsencrypt.org/directory"
        dashboard:
          username: admin
          password: admin

immich_env:
  user:
    password: "123456"
  data_storage:
    zfs_encryption_key: "12345678901234567890123456789012"
  container:
    postgres:
      config:
        db:
          password: immich-db-password

filebrowser_env:
  user:
    password: "123456"
  data_storage:
    zfs_encryption_key: "12345678901234567890123456789012"
  container:
    server:
      config:
        admin:
          username: admin
          password: adminadmin123*

photoprism_env:
  user:
    password: "123456"
  data_storage:
    zfs_encryption_key: "12345678901234567890123456789012"
  container:
    server:
      config:
        admin:
          username: admin # PhotoPrism does not allow to create users in the free version. This is also the user to use the application with.
          password: admin
    mariadb:
      config:
        db:
          password: photoprism-db-password
          root_password: photoprism-db-root-password

gitea_env:
  user:
    password: "123456"
  data_storage:
    zfs_encryption_key: "12345678901234567890123456789012"
  container:
    postgres:
      config:
        db:
          password: gitea-db-password

