---
domain: dev.homelab.mikemarti.ch
platform: alpine
processor_microcode_package: intel-ucode
superuser_method: sudo
service_data_filesystem: zfs
zfs_devices:
  - /dev/vdb
  - /dev/vdc

# This public key is the counterpart to the private ssh key found in the pi variable file. It is stored as an authorized
# key for the wol_poweroff_user, such that a remote actor with the private key counterpart can initiate a remote poweroff
# command through an unprivileged user. In order to not need to deploy all nodes simultaneously, a key pair was created
# ahead of time and stored in the variable files, as opposed to creating one during ansible execution time. The key
# presented here is intended for local development only and should not be used with real systems. For non-local
# environments a new ssh key pair can be created using ssh-keygen.
# DO NOT USE IN PRODUCTION UNDER ANY CIRCUMSTANCES!!
wol_poweroff_user_ssh_public_key_base64: c3NoLWVkMjU1MTkgQUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSUxreWNQQTZYV2pFTWZ0Ykx3MkVYSFFLZ01KMG93YVZVKzE1Y2NnYTBxRy8gbWlrZUBtaWtlLWhvbWUtbGludXgK

# Traefik
traefik_user_password: "123456"
traefik_ca_server: "https://acme-staging-v02.api.letsencrypt.org/directory"
traefik_dashboard_username: admin
traefik_dashboard_password: admin

# Immich
immich_user_password: "123456"
immich_db_password: immich-db-password

# Filebrowser
filebrowser_user_password: "123456"
filebrowser_admin_username: admin
filebrowser_admin_password: adminadmin123*

# PhotoPrism
photoprism_user_password: "123456"
photoprism_db_password: photoprism-db-password
photoprism_db_root_password: photoprism-db-root-password
photoprism_admin_username: admin # PhotoPrism does not allow to create users in the free version. This is also the user to use the application with.
photoprism_admin_password: admin

# Gitea
gitea_user_password: "123456"
gitea_db_password: gitea-db-password

