---
- name: "Ensure {{ gitea_user }} is created"
  ansible.builtin.import_role:
    name: infrastructure/user
  vars:
    user_name: "{{ gitea_user }}"
    user_password: "{{ gitea_user_password }}"

- name: Ensure gitea storage directory location exists
  ansible.builtin.import_role:
    name: infrastructure/service-data-directory
  vars:
    path: "{{ gitea_storage_directory }}"
    user: "{{ gitea_user }}"

- name: Ensure gitea is running
  become: true
  become_user: "{{ gitea_user }}"
  block:
    - name: Ensure gitea container network is created
      containers.podman.podman_network:
        name: "{{ gitea_network }}"
        driver: bridge
        recreate: false
        state: present

    - import_tasks: gitea-database.yaml
    - import_tasks: gitea-server.yaml

