---
- name: Configure server node
  hosts: server
  roles:
    - mirror
    - base
    - zfs
    - wakeonlan
    - firewall
    - traefik
    - service/immich
    - service/filebrowser
    - service/photoprism
    - service/gitea

