---
- ansible.builtin.import_role:
    name: infrastructure/build_vars
  vars:
    service: filebrowser

- name: "Ensure {{ filebrowser.user.name }} is created"
  ansible.builtin.import_role:
    name: infrastructure/user
  vars:
    user_name: "{{ filebrowser.user.name }}"
    user_password: "{{ filebrowser.user.password }}"

- name: Ensure filebrowser storage directory location exists
  ansible.builtin.import_role:
    name: infrastructure/service-data-directory
  vars:
    data_storage: "{{ filebrowser.data_storage }}"
    user: "{{ filebrowser.user.name }}"

- name: Ensure filebrowser is running
  become: true
  become_user: "{{ filebrowser.user.name }}"
  block:
    - name: Ensure filebrowser container network is created
      containers.podman.podman_network:
        name: "{{ filebrowser.container.network }}"
        driver: bridge
        recreate: false
        state: present

    - import_tasks: filebrowser-server.yaml

