---
- name: "Ensure {{ filebrowser_user }} is created"
  ansible.builtin.import_role:
    name: infrastructure/user
  vars:
    user_name: "{{ filebrowser_user }}"
    user_password: "{{ filebrowser_user_password }}"

- name: Ensure filebrowser storage directory location exists
  ansible.builtin.import_role:
    name: infrastructure/service-data-directory
  vars:
    path: "{{ filebrowser_storage_directory }}"
    user: "{{ filebrowser_user }}"

- name: Ensure filebrowser is running
  become: true
  become_user: "{{ filebrowser_user }}"
  block:
    - name: Ensure filebrowser container network is created
      containers.podman.podman_network:
        name: "{{ filebrowser_network }}"
        driver: bridge
        recreate: false
        state: present

    - import_tasks: filebrowser-server.yaml

